### ISSUE TITLE
Assignment 3: TCAS Part III

### ISSUE THREAD

**Issue by yheechan** [swtv-kaist/cs458-spring24#11]
Does instruction of 3.b from part III require us to generate a test case for all rows within the T/F table?
The example T/F table in the slides contain a test case for each row.

The instruction written in b.i only states to select test inputs to satisfy RACC and CACC.

I got confused because the instructions within the slide of Part III doesn't say anything about generating test cases for all cases of the predicate while the example table on the right hand side shows test cases for all cases.

**Comment by YoungseokCh** [comment]
Can you ellaborate about 'for all rows within the T/F table' and 'test cases for all cases'? I am not sure with the interpretation of term 'all'.

**Comment by yheechan** [comment]
## 1. Elaboration on original question
![image](https://github.com/swtv-kaist/cs458-spring24/assets/50125642/7242ab1b-532d-463c-bfab-870c70943dab)

This image above shows the T/F table given as an example in the Part III of the assignment slides.

> 'for all rows within the T/F table'
* Within this T/F table, it can be seen that each row (Unique cases of a predicate from the clauses it includes) has been assigned a test case or test input(e.i., t1 for row 1, t2 for row2. etc.)
* Therefore, I was wondering **whether the instruction require us to generate a test case for each row from T/F table of a single predicate**.

I think I may have confused because the test inputs table also shows test input ID as t1, t2, ... etc.
![image](https://github.com/swtv-kaist/cs458-spring24/assets/50125642/691d1e3b-1088-4891-9e78-c8c37841f965)


## 2. Additional question for clarification
Am I correct that we **do not** have to select test cases for **"all pairs"** of rows that satisfy RACC but just for one from existing pairs that satisfy RACC?

#### Example
* Target predicate: the T/F table given in the first image of the message.
* All pairs of rows that satisfy RACC for **active a**
    * { (row1, row5) , (row3, row7), (row4, row8) }
 * The single selected test inputs given in the example (in the slides) only includes for the pair (row1, row5) which are (t1, t5). The test inputs selected (shown in the slides) has been prepared in the image below.
![image](https://github.com/swtv-kaist/cs458-spring24/assets/50125642/55be7bcd-26d0-4987-9861-ba29dbd539e1)

**Comment by YoungseokCh** [comment]
1. For each predicate, you just need to write T/F table to show that selected test inputs satisfy RACC/CACC, not all testcases. Think of it as a material to support your choice of testcases.
2. You can select just one from existing pairs.

**Comment by swtv-kaist** [comment]
For clarification, you should make an input tuple containing 12 concrete input values and name the tuple as t1. Similarly, you should make another tuple t2 and so on.  At the same time, your selected input tuples should satisfy RACC. and CACC for each predicate (you should show it by using the truth table as shown in the HW#3 description).
