### ISSUE TITLE
[HW4] Counting the number of execution of branch

### ISSUE THREAD

**Issue by Mysigyeong** [swtv-kaist/cs458-spring24#12]
Is the default body execution do while statement considered as the execution of then branch?
For example
```c
int a = 0;
do {
    a++;
}while(a < 2)
```
In the above case, is the result (2, 1, a < 2) or (1, 1, a < 2)?
(# of execution of then branch, # of execution of else branch, conditional expression)

In addition, in the switch statement,
```c
int a = 150;
switch (a) {
case 150:
case 200:
break
}
```
Is it the execution number of case 200 is 1 or 0?

Thank you.

**Comment by YoungseokCh** [comment]
1. No, default body execution is not considered as then branch. In the example, the result is (1, 1, a<2).
2. The execution count of `case 200` is 0. Although it executes the body of `case 200`, the branch instruction from `switch` to `case 200` is never taken.
