### ISSUE TITLE
[HW3] Part III: predicate and clauses

### ISSUE THREAD

**Issue by leejy12** [swtv-kaist/cs458-spring24#13]
I want to ask to see if I'm on the right track.

The first predicate (line 72) is `!(Own_Below_Threat()) || ((Own_Below_Threat()) && (!(Down_Separation >= ALIM())))`.
It has two clauses, say `a = Own_Below_Threat()`, `b = Down_Separation >= ALIM()`,
and the predicate can be expressed as `p = ~a ∨ (a ∧ ~b)`.

So for this predicate, we have to draw a truth table for two clauses, right? (Total 4 cases).

Also, do we have to consider other input values other than those that directly affect each predicate?
For example, the first predicate `!(Own_Below_Threat()) || ((Own_Below_Threat()) && (!(Down_Separation >= ALIM())))` is only evaluated when `Non_Crossing_Biased_Climb()` is called AND `upward_preferred` (defined at line 69) is true. Do we have to make our test input such that the predicate at line 72 is "hit"?

**Comment by YoungseokCh** [comment]
> So for this predicate, we have to draw a truth table for two clauses, right? (Total 4 cases).
1. You need to draw truth table to only demonstrate that selected test inputs satisfy RACC/CACC. There is no other purpose for it.
> Do we have to make our test input such that the predicate at line 72 is "hit"?
2. Yes, you need to make the test input that reaches the line.

**Comment by leejy12** [comment]
Thank you very much!
