### ISSUE TITLE
[HW4] number of branches

### ISSUE THREAD

**Issue by leejy12** [swtv-kaist/cs458-spring24#14]
I'm trying to figure out how `example-kcov.c` results in 30 branches.
~~If I count the number of outgoing edges among nodes with two or more outgoing edges, I get 28 total. I'm wondering what I may have missed.~~

I've edited the graphs to account for what I missed.

`function f1`: 2 branches.
```mermaid
graph TD
  1 -- a == 1 --> 2
  1 -- else --> 3
```

`function f2`: 2 branches.
```mermaid
graph TD
  1 -- x > 10 --> 2
  1 -- else --> 3
  2 --> 4
  3 --> 4
```

`function main`: ~~24~~26 branches.
```mermaid
graph TD
  1 -- if (a == 1 || a == 3) --> 2
  1 -- else --> 3
  3 -- if (a == 2) --> 4
  3 -- else --> 5
  2 --> 6
  4 --> 6
  5 --> 6
  6 -- i < 10 --> 7[7; a += i]
  7 --> 6[6; for]
  6 --> 8[8; while]
  8 -- a < 100 --> 9
  9 --> 8
  8 --> 10[10; switch]
  10 -- case 100: --> 11
  10 -- case 200: --> 12[12: ternary]
  10 -- default: --> 13
  12 -- a == 3 --> 14
  12 -- else --> 15
  14 --> 16
  15 --> 16
  11 --> 17
  13 --> 17
  16 --> 17
  17 --  while (a == 0) --> 10
  17 --> 18[18; ternary]
  18 -- a > 1 --> 19
  18 -- else --> 20
  19 --> 21
  20 --> 21
  21 -- if (a>1 ? a-1 : a) --> 22
  21 --> 23[23; switch]
  22 --> 23
  23 -- case 150: --> 24
  23 -- case 250: --> 25
  23 -- ImpDef --> 26
  26 --> 27
  24 --> 27["27; FOO(x)"]
  25 --> 27
  27 -- x > 100 --> 28
  27 -- else --> 29
  28 --> 30
  29 --> 30
  30 -- while(0) --> 27
  30 --> 31["31; f2(a)"]
  31 --> 32
```

**Comment by leejy12** [comment]
Another question. Given this function:

```c
void foo() {
  // no if, for, while
}
```

Does this code have 0 branch or 1 branch? By the definition given at https://github.com/swtv-kaist/cs458-spring24/issues/9#issuecomment-2056806071, it should be 0 but intuitively, I think 1 branch makes more sense.

**Comment by YoungseokCh** [comment]
Thank you for the detailed question utilizing mermaid graph visualizer.
For the first question, there is no `else if` statement in C. It is just an else statement that has another body statement.
```c
	if( a==1 || a==3) {
		a =  2;
	} else if ( a == 2){
		a = 1;
	} else {
		a = 4;
	}	
```
This is equivalent to following code with brackets.
```c
if (a==1 || a==3) {
	a = 2;
} else {
	if (a == 2) {
		a = 1;
	} else {
		a = 4;
	}
}	
```
Therefore, this part has four branches, not three.

Also, for the second switch case statement, there is an **implicit default** branch for the case when no cases condition meet.

These are the two missing branches you are looking for.

**Comment by YoungseokCh** [comment]
For the second question, Could you explain why you thought 1 branch makes more sense?

**Comment by leejy12** [comment]
Thank you for pointing out where I missed!

> For the second question, Could you explain why you thought 1 branch makes more sense?

I thought of the number of branches as "number of possible execution paths". So an empty function like `void foo() {}` will have one branch as there's only one possible execution path. Adding a single `if` statement would increase it to 2.

**Comment by YoungseokCh** [comment]
An empty function in the example has 0 branches since there is no branching instruction in the code. I think you are trying to define number of branches formally based on induction principle, but it's not how it works.

Does it answer your question?

**Comment by leejy12** [comment]
Yes, thank you.
