### ISSUE TITLE
How to find GICC?

### ISSUE THREAD

**Issue by leejy12** [swtv-kaist/cs458-spring24#15]
![image](https://github.com/swtv-kaist/cs458-spring24/assets/60320918/a5cd2de3-05bf-4048-8b2e-bce312c37296)

I'm having trouble understanding how to find GICC.

For example finding GICC for major clause `b`:

| `b` \ `p` | `T` | `F` |
| --------- | --- | --- |
| `T`       | 1    | 2, 5, 6 |
| `F`       | 3, 4 | 7, 8 |

So I think GICC for `b` is
- (1, 3), (1, 4) for `p=T`
- {2, 5, 6} x {7, 8} for `p=F`

I don't understand why these 
- (1, 4) for `p=T`
- (2, 7), (2, 8) for `p=F`

aren't valid GICC for `b`.

**Comment by leejy12** [comment]
Oh, I think it's because `p_b = T` in cases 2 & 4.

**Comment by YoungseokCh** [comment]
You are right. In GICC(General **Inactive** Clause Coverage), the major clause should not determine the predicate.
