### ISSUE TITLE
[HW4] Functions from stdio.h

### ISSUE THREAD

**Issue by frogfrog2** [swtv-kaist/cs458-spring24#17]
I wrote down kcov-branch-identify and executed it with example-kcov.c, but the output was very weird. It contained lots of functions from stdio.h header file. In order to get the expected output, is there any fancy way to exclude the functions from stdio.h? Any help would be appreciated.

**Comment by leejy12** [comment]
I solved it by getting the filename in which the `FunctionDecl` is declared, and not print the function name in `VisitFunctionDecl`, depending on the filename.
