### ISSUE TITLE
[HW4] Situation where different `<f>-cov` programs are run.

### ISSUE THREAD

**Issue by leejy12** [swtv-kaist/cs458-spring24#19]
I think it will be problematic if different `kcov` modified programs are run when `coverage.dat` already exists.

For example
1. `foo-cov.c` compiles to `foo-cov` program.
2. `bar-cov.c` compiles to `bar-cov` program.
3. Run `foo-cov`. It generates `coverage.dat`.
4. Run `bar-cov`. It attempts to update `coverage.dat`, which includes information from `foo-cov`.

This will lead to a messy `coverage.dat`.

Can we just disregard this kind of situation?

**Comment by YoungseokCh** [comment]
You can assume that user delete old coverage.dat when measureing the coverage of different file.
