### ISSUE TITLE
[HW4] File name(PrintBranches?) and fatal error: 'stddef.h' file not found

### ISSUE THREAD

**Issue by Jae-Woo-Jung** [swtv-kaist/cs458-spring24#21]
I have two simple questions. 
1. The example is a result of ./PrintBranches example-kcov.c
But make file makes kcov-branch-identify instead of PrintBranches.

Then, should I change the file name of kcov-branch-identify to PrintBranches?

2. When I execute ./kcov-branch-identify example-kcov.c, the result starts with error message: 
In file included from example-kcov.c:3:
/usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found
#include <stddef.h> 

How can I solve this porblem? I have no right for /var/lib directory. 

<img width="866" alt="image" src="https://github.com/swtv-kaist/cs458-spring24/assets/48016508/a0703482-1795-4998-b591-b6779e36ce46">

**Comment by leejy12** [comment]
2.
```
$ find /usr -name stddef.h
/usr/include/linux/stddef.h
/usr/src/linux-hwe-6.5-headers-6.5.0-28/include/uapi/linux/stddef.h
/usr/src/linux-hwe-6.5-headers-6.5.0-28/include/linux/stddef.h
/usr/src/linux-hwe-6.5-headers-6.5.0-25/include/uapi/linux/stddef.h
/usr/src/linux-hwe-6.5-headers-6.5.0-25/include/linux/stddef.h
/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h
/usr/lib/llvm-13/include/c++/v1/stddef.h
/usr/lib/llvm-13/lib/clang/13.0.1/include/stddef.h
```

Try using one of the above include paths so the program can find `stddef.h`.

**Comment by Jae-Woo-Jung** [comment]
Then, is it allowed to change const char *include_paths[]?

**Comment by leejy12** [comment]
Yes, the homework explicitly says so.

```
Note 1. If your program fails to find header files of a target program (grep.c), you have to modify 
include_paths (line 137) in the initialization part of the kcov-branch-identify.cpp template file.
```

**Comment by Jae-Woo-Jung** [comment]
Thank you!
