### ISSUE TITLE
[HW4] Location of ImpDef.

### ISSUE THREAD

**Issue by Jae-Woo-Jung** [swtv-kaist/cs458-spring24#22]
I confuse how to specify the location of ImpDef. (Line and Col).

Although the given example "ImpDef" corresponds to the simple case, there is ambiguity in the location in many cases. 

The switch statement can be indented several times or it is in the scope of other statements such as switch, for, or while statements.
Then, how to specify or calculate the line/col of ImpDef.?

One candidate is:
Is it Line: (line of SwitchStmt)-1  and Col: (Col of SwitchStmt)?

**Comment by leejy12** [comment]
I think location of ImpDef is the same as the location of `SwitchStmt`.
In `example-kcov.c`, ImpDef is reported as line 68, column 2.

**Comment by Jae-Woo-Jung** [comment]
Oh, I see. The confusion was due to the difference between the annotation of example-kcov.c and the output written in HW4-1. 
Thanks.
