### ISSUE TITLE
[HW4] How to skip visiting child statements?

### ISSUE THREAD

**Issue by leejy12** [swtv-kaist/cs458-spring24#23]
When traversing the AST, how can I skip traversing a `Stmt`'s child nodes? If I return `false` from `VisitStmt`, it ends the entire traversal, but I want it to continue with its sibling nodes.

Any hint would be appreciated...

EDIT: I managed to work around my problem, but I still would like to know how to achieve this.

**Comment by YoungseokCh** [comment]
To my knowledge, there is no way to skip visiting the child nodes in current clang RecursiveASTVisitor.
By default, it traverses AST with preorder, and returning false aborts the entire traversal.

**Comment by leejy12** [comment]
😔 I see, thank you.

**Comment by Jae-Woo-Jung** [comment]
One trick is that you can define a global variable 
int depth, 
bool isSkipChild

Then, dynamically assign those variables and skip if isSkipChild is true. But still, it visits children.
