### ISSUE TITLE
[HW4] Should I throw an error for ./kcov grep.c?

### ISSUE THREAD

**Issue by Jae-Woo-Jung** [swtv-kaist/cs458-spring24#24]
I assumed that kcov always get input of the from <f>.i

Should I handle error cases such as no input, multiple input files, wrong file type?

**Comment by YoungseokCh** [comment]
No, you don't need to handle such cases.

**Comment by Jae-Woo-Jung** [comment]
Do you mean I should not throw an error when input file is of the form <f>.c?

If I can throw an error, then according to the Question 6, I should test kcov with test input files including grep.c by using gcov.
Is allowed to replace grep.c by grep.i?
Or should I just test ./kcov grep.c even though it throws an error?

**Comment by YoungseokCh** [comment]
I interpret your question as having two parts - the meaning of `grep.c` in Q6, and the input domain of `kcov`.

1. `grep.c` in the problem description means `kcov grep.i`, the preprocessed file of `grep.c`
2. You can assume `kcov` only receives the `*.i` preprocessed file when testing it and measuring the coverage.
