### ISSUE TITLE
[HW4] What should be printed for condition expression of `for (;;)`?

### ISSUE THREAD

**Issue by leejy12** [swtv-kaist/cs458-spring24#25]
In this for-loop:

```
for (;;) {}
```

what should be the condition expression? Can we just print nothing? Or perhaps something like `<true>` because it's an infinite loop?

**Comment by YoungseokCh** [comment]
You can print nothing although it means true in this case implicitly.

**Comment by YoungseokCh** [comment]
For the people who want to print it in a different way, we also allow other ways to express it as appropriate such as `<true>`, `NULL`, etc.
