### ISSUE TITLE
[HW4] Do we have to flush `coverage.dat` on abnormal process terminations?

### ISSUE THREAD

**Issue by hotmandu** [swtv-kaist/cs458-spring24#26]
On gcov, it seems that gcov does not update .gcda files when a process terminates abnormally,
such as by `abort()` or `_exit()`. Note that it is different from `exit()`.
Should kcov update the coverage data file on these irregular cases?
Or just updating data files only on `exit()` and `return` on `main()` is sufficient?

**Comment by YoungseokCh** [comment]
Since handling exceptional case is not written in the homework description, both ways are treated as correct.

**Comment by hotmandu** [comment]
Thanks!
