### ISSUE TITLE
[HW4] Strange behavior of Rewriter.ReplaceText

### ISSUE THREAD

**Issue by Jae-Woo-Jung** [swtv-kaist/cs458-spring24#27]
The original code is line 64 of example-kcov.c
	if ( a>1 ? a-1 :a ) 

I made two Ranges, condRange1 and conddRange2, which implies "a>1 ? a-1 :a" and "a>1" respectively.
More specifically, the output of
            llvm::outs() << "If Start location: " << condRange1.getBegin().printToString(srcMgr) << "\n";
            llvm::outs() << "If End location: " << condRange1.getEnd().printToString(srcMgr) << "\n";
is
If Start location: example-kcov.c:64:7
If End location: example-kcov.c:64:18

And the output of
            llvm::outs() << "?: Start location: " << condRange2.getBegin().printToString(srcMgr) << "\n";
            llvm::outs() << "?: End location: " << condRange2.getEnd().printToString(srcMgr) << "\n"; 
is
?: Start location: example-kcov.c:64:7
?: End location: example-kcov.c:64:9

And I executed the following statements.
TheRewriter.ReplaceText(condRange1, "   56789");
TheRewriter.ReplaceText(condRange2, "abcdef");

Then, the result is

	if ( abcdef6   56789 )

I can't understand this phenomenon. Why there is 6 right after "f"?

**Comment by leejy12** [comment]
I think it's because you're overwriting over a range that's already been overwritten/replaced. I'm just guessing, but that may not be a well-defined usage of clang libraries.

Have you tried `InsertText`/`InsertTextAfter`? I only used these functions.

**Comment by Jae-Woo-Jung** [comment]
I gave up using replace method because of its mysterious behavior. 
Thanks for your advice.
