### ISSUE TITLE
[HW4] Including headers in `.i` files does not seem to work..?

### ISSUE THREAD

**Issue by hotmandu** [swtv-kaist/cs458-spring24#28]
To make sure some header are included, I wrote `#include` directives at the beginning of the output `-cov.c` files.
(Following from [this discussion](https://github.com/swtv-kaist/cs458-spring23/issues/18))
However, when I try to compile it, gcc refuses because of conflictions by duplicate declarations.
Below is the part of the compilation log.
```
In file included from /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h:23,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:227,
                 from /usr/include/stdlib.h:395,
                 from ../grep/grep.c:48:
/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h:94:8: error: redefinition of ‘struct __pthread_cond_s’
   94 | struct __pthread_cond_s
      |        ^~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h:23,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:227,
                 from /usr/include/stdlib.h:395,
                 from /usr/include/errno.h:38,
                 from ../grep/grep.c:35:
/usr/include/x86_64-linux-gnu/bits/thread-shared-types.h:94:8: note: originally defined here
   94 | struct __pthread_cond_s
      |        ^~~~~~~~~~~~~~~~
```
The solution provided does not works... Could you give a hint on this?

**Comment by leejy12** [comment]
I solved the issue by checking if adding `#include` directives to original source file is necessary.

For example, try to look for differences between `*.i` files that does or does not include `<stdio.h>`.

**Comment by hotmandu** [comment]
Thanks! I've solved the issue by manually checking.
But I still wonder if there exists simpler way to do this..

**Comment by YoungseokCh** [comment]
There is no simple way to deal with this problem in general.
One way is to copy the library code, rename the variables with common prefixes(such as `__kcov_`), and let kcov to instrument it. However, it's still complicated.
