### ISSUE TITLE
[HW4] segmentation fault What should I do?

### ISSUE THREAD

**Issue by Jae-Woo-Jung** [swtv-kaist/cs458-spring24#29]
I got segmentation fault when ./kcov grep.i

./kcov example-kcov.c  works well. 

The segmentation fault happens during traversing Declaration, when meeting the node whose line is 1362, union pthread_attr_t. 
Although I delete union pthread_attr_t, still there are many other Decl that causes Segfault.

I don't know how to handle this...

<img width="694" alt="image" src="https://github.com/swtv-kaist/cs458-spring24/assets/48016508/728d40ca-7f3c-49bb-8fec-79d891d19283">

**Comment by leejy12** [comment]
I can't tell what you're trying to achieve in `VisitStmt`, but segfault is most likely caused by null pointer dereference. Try looking for where you dereference a pointer without checking its value.

**Comment by hotmandu** [comment]
As `make` builds `kcov` with `-g` option, you can use `gdb` to get backtrace or to do detailed debugging.

**Comment by Jae-Woo-Jung** [comment]
I found that the problem was traversing twice. 
Also, for(;;) was problemtic. Thank you.
