### ISSUE TITLE
Prime-path coverage and All-DU-paths coverage for infinite graph?

### ISSUE THREAD

**Issue by Jae-Woo-Jung** [swtv-kaist/cs458-spring24#3]
Consider the following graph G,

the node set: N={0, 1, 2, 3, ....}  (i.e. non-negative integer set),
initial node set: N_0={0, 2},
final node set: N_f={1, 3}, 
edge set: E={ (n, n+1): n∈N}
def(0)=def(2)=use(1)=use(3)={x}
use(0)=use(2)=def(1)=def(3)={ } 
(For other nodes, there's no variable def and use.)

Then, TR of ADUPC is {[0, 1], [2, 3]}.
But the set of all prime paths is just an empty set since there is no prime path of G. 

So, {[0, 1]} satisfies PPC and does not satisfy ADUPC. 

Here, a prime path should have a finite length, but any finite path is a proper subpath of some path. (Any set contains an empty set.)

So, should we assume that a graph of HW1-3 has finite nodes?

**Comment by swtv-kaist** [comment]
> So, should we assume that a graph of HW1-3 has finite nodes?

Yes, you can assume that a graph is finite.
