### ISSUE TITLE
[Hw5] About determining `XX.YY` index of branch instructions of multiline ifs

### ISSUE THREAD

**Issue by tncks0121** [swtv-kaist/cs458-spring24#30]
In Problem 3-E, there is a branch with `311.2 -> 18,2`, which corresponds to this code:

```
311:  if (bufmapped && bufoffset % pagesize == 0
312:      && bufstat.st_size - bufoffset >= bufalloc - bufsalloc)
```

Due to short-circuit, I think there are 3 `br` instructions A, B, C corresponding to the `if` statement, that do something like

```
A: if bufmapped then goto B, else goto X
B: if bufoffset % pagesize == 0 then goto C, else goto X
C: if bufstat.st_size - bufoffset >= bufalloc - bufsalloc then goto D, else goto X
```

A and B corresponds to line 311, but it seems C corresponds to line 312. So without knowing the semantics of the C code, I'm not sure how to determine how C is related to line 311.

For multiline `if` or `?:`s, is it intended that first line of the whole large statement should be used to indicate the line number?

**Comment by YoungseokCh** [comment]
~~Yes, the first line of the whole statement should be used to indicate the line number. In this example, because there is an `if` on line 311, condition C is compiled into a branch instruction. Thus we write `311.2->18.2` although condition C is located in line 312.~~

**Comment by yheechan** [comment]
May I have clarification of branch line number identification in the following toy example code?

```
1: int x = 2;
2: if (x == 2) {
3:      printf("Hello world\n");
4: else if (x == 1) {
5:      printf("Bye Bye world\n");
6: }
```

I believe there are two branches, which are:
```
A: x == 2 at line 2
B: x == 1 at line 4
```

What should be the branch line number identification for these branches? (where in X.Y, X is the location of branch condition and Y is the index.
Is it correct if it is:
```
2.0
2.1
```
or is it correct if it is:
```
2.0
4.0
```

**Comment by YoungseokCh** [comment]
The latter one
```
2.0
4.0
```
is correct in this case. The C code is equivalent to:
```
1: int x = 2;
2: if (x == 2) {
3:      printf("Hello world\n");
4: else { if (x == 1) {
5:      printf("Bye Bye world\n");
6: } }
```
The difference is the curly bracket after the else token. You can see that the if statement for `x==1`  ranges from line 4 to line 7. Therefore, `if (x==1)` branch begins at line 4.

**Comment by tncks0121** [comment]
Is it really possible to find the "enclosing if" or "enclosing while" of a branch instruction from LLVM IR API? I tried multiple things in LLVM API and used them in weird ways, but didn't manage to find a logic that applies to all possible C code I can think of. 

If my program doesn't correctly find the line number of branches inside multiline ifs, will it get 0 points on problem 4 since the line numbers are not correct?

**Comment by tncks0121** [comment]
For example, if a code is like:

```c
01: do
02: 
03: {
04: 
05:  a++;
06: 
07: }
08: 
09: while 
10:
11: 
12: (
13: 
14: 
15: a < 100 ||
16:  a < 200
17: 
18: 
19: );
```

I have three questions:

- What is the expected line number of the `br` instruction created by `a < 100`? Is it 9 or 12 or 15?
- What is the expected line number of the `br` instruction created by `a < 200`? Is it 9 or 12 or 15?
- Is it really possible to locate the line number of the "while" when considering the `br` instruction of `a < 100` or `a < 200`?

**Comment by YoungseokCh** [comment]
Basically, The logic for getting source locations of corresponding `br` and `switch` instructions is not complicated at all. **Probably the simplest implementation will be correct.**

Also, we will not deduct the score related to this multi-line issue. It will be fine if it is **well-ordered** and the corresponding line numbers are **located in such conditionals**.

I found my previous answer https://github.com/swtv-kaist/cs458-spring24/issues/30#issuecomment-2104726201 is adding confusion, so please ignore it. Sorry for that.

**Comment by tncks0121** [comment]
Thanks for the clarification. :D
