### ISSUE TITLE
[HW 5] Intwrite fails on grep?

### ISSUE THREAD

**Issue by Ahmadsm2005** [swtv-kaist/cs458-spring24#31]
in the grep file directory, I tried to run the following:

clang --ld-path=ld.lld -fno-experimental-new-pass-manager grep.c ../../lib/intwrite-rt.o -g -O0 -Xclang -load -Xclang ../../lib/libintwrite.so -o grep

But I am getting quite strange warnings and errors as follows:
![image](https://github.com/swtv-kaist/cs458-spring24/assets/31192081/4728b745-8ca6-433e-82e8-0601dc3cd1c0)

But it works perfectly fine on the example.c. I was building my ccov while only testing on example.c but even intwrite does not work with grep. Is there something wrong?

**Comment by swtv-kaist** [comment]
Would you attach a screen snapshot that shows errors, not warnings?
Thanks

**Comment by Ahmadsm2005** [comment]
Actually for some reason, grep folder was corrupted on the machine(might be that I made a mistake while uncompressing it). It now works!

Thank you!
