### ISSUE TITLE
[HW6] How to find coverage info with `gcov`?

### ISSUE THREAD

**Issue by leejy12** [swtv-kaist/cs458-spring24#32]
Hello, I want to see if I understood the problems correctly.

In Problem 1(c)(iii), it asks to find the test input with best graph coverage.
After running `afl-fuzz` for 30 minutes, it generated 664 test inputs. Then do I have to check coverage for each of those inputs?

Step-by-step

1. Compile `grep.c` for AFL and gcov.
```
$ afl-clang-lto grep.c -o grep
$ gcc -O0 -coverage grep.c -o grep-cov
```
2. Fuzz with 3 seeds (4580, 4581, 4582), 30 minutes each.
```
$ afl-fuzz -V 1800 -s 4580 -i <input_seeds> -o <output_dir> -- ./grep .... @@
```
3. Run `grep-cov` with all test inputs (hundreds!) in `<output_dir>` and find the best one.

Is my understanding correct?

**Comment by YoungseokCh** [comment]
Yes, you need to run each inputs with grep-cov binary, and find the best input that reaches highest coverage.

**Comment by leejy12** [comment]
Thank you!
