### ISSUE TITLE
[Lecture Slides] Could you update lecture slides about fuzzing? (lec41 and lec42)

### ISSUE THREAD

**Issue by metamon123** [swtv-kaist/cs458-spring24#35]
Hi,

I found that some fuzzing lecture slides look like not updated yet. Could you check below lecture slides?
1. lec41, both [pdf](https://github.com/swtv-kaist/cs458-spring24/blob/main/4-fuzzing/lec41-intro-to-fuzzing-v2.pdf) and ppt
If I remember correctly, **contents of uploaded version and classroom version are slightly different.** (ex. In classroom, last page has more contents compared to uploaded version) If you don't mind, could you upload classroom version?
2. lec42, [pdf](https://github.com/swtv-kaist/cs458-spring24/blob/main/4-fuzzing/lec42-fuzzing_with_afl%2B%2B-v3.pdf) only
For lec42, **still the wrong pdf is uploaded** (lec43 - POWER) while correct pptx file is uploaded. Could you upload the correct pdf?

Thanks!

**Comment by swtv-kaist** [comment]
Oops, I am sorry that I missed your comment.  
I have uploaded corret versions of the slides at the course home page now.

**Comment by metamon123** [comment]
Thank you :)
