### ISSUE TITLE
[HW6] what is # of unique paths executed?

### ISSUE THREAD

**Issue by inseok-yeo** [swtv-kaist/cs458-spring24#37]
I am confused of what it means, and where i can find it.

Thank you!

**Comment by YoungseokCh** [comment]
1. Strictly speaking, path is defined as the sequence of instructions a testcase executed. In world of fuzzing, it is approximated as the **edge hitcount bitmap**, so you can simply interpret it as unique map coverage.

2. The number of unique paths corresponds to **how many unique paths were found during the entire fuzzing campaign**. Keep in mind that fuzzing runs a genetic algorithm that keeps all the testcases that explores unseen path as corpus. You can inspect the AFL++ output directory to find `# of unique paths`.

**Comment by tncks0121** [comment]
About answer 2, may I ask in that case how "# of unique paths" is different to the number of test cases, or `corpus_count`?

**Comment by YoungseokCh** [comment]
Indeed, they are identical. I think we made a mistake when introducing Problem 2-(c)(ii). Thanks for pointing it out!
