### ISSUE TITLE
[HW6] Regarding extra credits for highest brangh coverage

### ISSUE THREAD

**Issue by YoungseokCh** [swtv-kaist/cs458-spring24#38]
Hello, since I got a question by an email, I would like to share the response in public.

**Question**
> 3 students who have achieved the highest branch coverage (reported by gcov) w/ ANY methods will get extra points

Does this sentence mean that the three students who achieved the highest branch coverage are the three highest results from problem 1,2,3, or can additional methods be used?

For example, if I run the fuzzing for 1 hour instead of 30 minutes with the settings in problem 3 and get higher coverage, can I submit that as an answer to the extra problem?

**Answer**
For the extra credit, you don't need to set a time limit of 30 minutes for fuzzing as we did in the previous question. **Just provide a set of test cases and methodologies that maximizes coverage in some way and report the coverage**. (Of course, students should not collaborate with each other)

Regarding this assignment, we expect competition for computing resources as the deadline approaches, so please start early and avoid excessive resource consumption. Please be nice to each other. The server administrator may kill some processes which taking too much resourses for long time.

**Comment by inseok-yeo** [comment]
How should we submit the extra points part? is it okay if we just submit the result, or should we write down all the fuzzing settings that we used?

**Comment by YoungseokCh** [comment]
Please write what you have done to get the coverage on the report for that extra part.

Also, it is worth to mention that fuzzing is not the only way to get the highest coverage. For example, you may manually add testcases to the output corpus produced by fuzzing. Do whatever you want to finish the assignment.
