### ISSUE TITLE
[HW2] Some minor questions

### ISSUE THREAD

**Issue by leejy12** [swtv-kaist/cs458-spring24#4]
Hi, I have some minor questions about homework 2.

1. Was there a minimum requirement for achieving branch coverage? E.g. at least 50% for `Taken at least once`.
2. My `test_script` contains a lot of test cases, how can I pinpoint which one achieves the greatest branch coverage? Do I have to run each test case separately and find the best result? Or is there a simpler (automated) way?

Thank you.

**Comment by YoungseokCh** [comment]
1. In 1-D, it says "Your test cases should achieve higher than 50% branch coverage".
2. You should find your own way to solve this. Basically, it requires you to run all the testcases. You may write a script from scratch to automate it.

**Comment by leejy12** [comment]
Thank you for your answer.
