### ISSUE TITLE
Haster3 is dead!!

### ISSUE THREAD

**Issue by Luna0413** [swtv-kaist/cs458-spring24#41]
Haster3 server is dead.

We have two more people in haster3 server than other servers.
We cannot execute our fuzzer and execution speed sometimes go down than normal environment.
![image](https://github.com/swtv-kaist/cs458-spring24/assets/80435715/fc489abc-5f04-4c2d-8577-cc01fd92490a)

Please recover the Haster3 ASAP.

**Comment by ji-wlsk** [comment]
<img width="1266" alt="image" src="https://github.com/swtv-kaist/cs458-spring24/assets/165860381/261e26d4-9795-4a8f-a83e-445275594547">
I think I have same issue..

**Comment by ji-wlsk** [comment]
<img width="407" alt="image" src="https://github.com/swtv-kaist/cs458-spring24/assets/165860381/596fd6e1-633b-40e4-94b6-6ea39a0720aa">

I think I am in same trouble..

**Comment by choehojun** [comment]
Me too. I'm also in haster3 server, and server is dead now. Now, even though the server is turned on, the resource utilization is very high, so it is difficult to do the homework normally.

**Comment by ji-wlsk** [comment]
<img width="638" alt="image" src="https://github.com/swtv-kaist/cs458-spring24/assets/165860381/dea7e8b6-3243-4321-a9bc-385397a1c603">

It seems like I'm in same troubles..

**Comment by ahcheongL** [comment]
Can you check if someone is using the machine with `ps aux` command?

**Comment by swtv-kaist** [comment]
1.  Please run **only 1 instance of AFL++** per person.  I am sorry that I forgot to tell you this guideline at the class.

2.  This is because no one can run AFL++ if all CPU cores of a server (16 for a haster machine) are occupied by AFL++ instances.

**Comment by Luna0413** [comment]
Someone's process has been in operation since the 21st or 22nd. Probably hasn't shut down.
It consume more than 50% cpu resource. Please terminate processes.

**Comment by YoungseokCh** [comment]
We cleaned up old processes in haster3 and checked AFL++ is available now. Thank you.

**Comment by Luna0413** [comment]
I cannot connect to haster3 server.

**Comment by YoungseokCh** [comment]
CPU utilization of haster3 machine is very high now. Now it is recovered.

You may try running AFL++ in local if you can have any Linux machine or Docker environment - https://aflplus.plus/docs/install/.

Sorry for the inconvenience.

**Comment by YoungseokCh** [comment]
Now CPU/memory utilization is much decreased and the machine is in stable state.
We will monitor haster3 machine for a while.

**Comment by Luna0413** [comment]
When I terminated fuzzer with ctrl + c, some process for alf-fuzz didn't terminate and it still consumes lots of resource.
Even though I tried to kill those processes with kill -9 pid, I couldn't kill those processes. How can i do for this problem?

**Comment by YoungseokCh** [comment]
I am not able to answer it exactly without the detailed information.
1. There will be a way to kill processes by yourself. You have full control on every process you have spawned, so there will be a way to kill them.
2. Maybe your AFL++ driver is implemented in wrong way which spawn unnecessary processes. For example, do not call linux command in your driver to run grep.
