### ISSUE TITLE
[Announcement] Server Status

### ISSUE THREAD

**Issue by YoungseokCh** [swtv-kaist/cs458-spring24#42]
Server resource issues are particularly common for this challenge because fuzzing is resource intensive. 

**Make sure to back up your data regularly,  and please avoid spawning too much processes** when you fuzz and measure coverage. Specifically, 

1. Each person can only run one instance of AFL++. (multiprocess option is not allowed)
2. Avoid multiprocessing when you replay your testcases. Coverage can be measured in few minutes even if you run testcases sequentially.

You can consider fuzzing in your own machine if you have linux machine or docker envionment - follow https://aflplus.plus/docs/install/ to install it.

We will share the server issue in this thread until the homework deadline.

Thank you.

**Comment by tncks0121** [comment]
Is `haster1` is okay now? I cannot suddenly access haster1 with SSH about 10~20 minutes ago.

**Comment by tncks0121** [comment]
```
$ ssh -v (my username)@haster1.kaist.ac.kr
OpenSSH_9.6p1, LibreSSL 3.3.6

... (removed)
debug1: Connecting to haster1.kaist.ac.kr port 22.
debug1: Connection established.
... (removed)
debug1: Local version string SSH-2.0-OpenSSH_9.6
debug1: kex_exchange_identification: banner line 0: Exceeded MaxStartups
kex_exchange_identification: Connection closed by remote host
Connection closed by (ip) port 22
```

**Comment by YoungseokCh** [comment]
haster1's resource usage was high overnight, now it is dropped since 2pm. Thank you for the report.

**Comment by aney666** [comment]
I think haster2 is dead. Can you check for us?.. I can't to connect haster2 server.

**Comment by Ahmadsm2005** [comment]
It seems like in my last fuzzing case, there is a problem with the speed of the fuzzing. It is around x8 slower!(Haster2)

![image](https://github.com/swtv-kaist/cs458-spring24/assets/31192081/5ec18d49-5d7e-4945-b6e2-6b36eb08d0b4)

**Comment by YoungseokCh** [comment]
Can you explain what the 8x slowdown in fuzzing performance is compared to? haster2's resource usage is not that high now.

**Comment by Ahmadsm2005** [comment]
I'd assume the number of executions. Normally, it should be a bit over 1.5M at around this time. Also, the map density is extremely bad for that (4582) compared to the other 2(P3T1,P3T2(4580,4581)) which is over 70% for around the same time.

I will try to re-run it now but I might submit the H.W 1 hour late
