### ISSUE TITLE
[HW6] Submission of AFL++ outputs

### ISSUE THREAD

**Issue by frogfrog2** [swtv-kaist/cs458-spring24#43]
The instruction tells us to submit one zip file that contains AFL++ outputs. Does this mean we have to submit each 'out' directory itself created by AFL? Since the files in 'queue' directory have colons in their names, I'm having a hard time transferring them to my local server.

**Comment by YoungseokCh** [comment]
Yes, the out directory of AFL++ is required.

**Comment by frogfrog2** [comment]
Am I allowed to rename the files which have colons in their names? I'd like to do so only to solve the above problem.

**Comment by YoungseokCh** [comment]
If file transfer is the only issue issue, I think your problem can be easily resolved by using copy-directory command through ssh (such as `scp -r`), or you may use compression command (tar, zip) to make them into one file.

**Comment by frogfrog2** [comment]
Actually I failed with 'no such file or directory' messages for problematic files using scp -r command... I'll try compression command!
