### ISSUE TITLE
[Hw7] In Part 2 Problem 4, what is an "symbolic execution path" and how to show them?

### ISSUE THREAD

**Issue by tncks0121** [swtv-kaist/cs458-spring24#46]
I think "execution path" can be interpreted as the sequence of nodes of the control flow graph visited in the real execution.

I also think the symbolic path formula can be obtained by collecting all necessary conditions to visit each node in the execution path.

However, I'm not sure what an "symbolic execution path" means exactly.

In particular, I'm not sure how to _show_ them in Part 2 Problem 4. It would be nice if there is an example of a symbolic execution path for a very simple program like in https://github.com/swtv-kaist/cs458-spring24/blob/main/5-concolic-testing/lec33-crown-Examples-v2.pdf

**Comment by swtv-kaist** [comment]
You can find all information necessary for HW#7 from the crown tutorial lecture slides ;-) 
![image](https://github.com/swtv-kaist/cs458-spring24/assets/29851315/28b1d59d-1964-441f-8541-62712f62114b)

![image](https://github.com/swtv-kaist/cs458-spring24/assets/29851315/1f97185c-5d03-4cf5-be79-94607dce043e)

**Comment by tncks0121** [comment]
I did read those slides, but there is no exact term "symbolic execution path", so I just wanted to be sure. Will specifying list of (branch id, condition) be enough?

Thanks for answering in such a late time, and I'm sorry if this issue interrupted

**Comment by swtv-kaist** [comment]
You can consider "symbolic path formula", "symbolic execution", "symbolic path", "symbolic execution path" as a same term.  

> Will specifying list of (branch id, condition) be enough?

Yes. You can write a symbolic execution path in a human readable format as shown in the output of print_execution
Ex. (a >0 ) /\ (b > 0) /\ (c>0) /\ (a!=b) /\ (a==c)

**Comment by tncks0121** [comment]
Thanks for the clarification!
