### ISSUE TITLE
[HW7] print_execution command

### ISSUE THREAD

**Issue by yheechan** [swtv-kaist/cs458-spring24#48]
I am having a problem with the command `print_execution`.

The result from `print_execution` only shows results from the **last** input generated from the set of inputs in `test-dir/` directory even though inputs other than the last input is copied to `input` file for `print_execution`.

As an example, lets say the input of target program takes 2 integer values as symbolic values for concolic testing.
* we generate 10 inputs using `crown_crown`
* the input values of `input.1` is **23** and **1**
* the input values of `input.10` (that last generated input by crown) is **12** and **3**

Then I copy `test-dir/input.1` to the `input` file in which `print_execution` uses to execute and show results.
However, when doing so (copying `test-dir/input.1` to `input`), `print_execution` shows output with input values as **12** and **3** which is from `test-dir/input.10`.

Has any other classmates experience such problem? Or have solutions for utilizing `print_execution`?

Thank you.

**Comment by moonzoo** [comment]
You have to execute your instrumented target program before using ```print_execution```
This is because ```print_execution``` actually prints ```szd_execution``` in a human readable format, which is generated by executing an instrumented target program.

![image](https://github.com/swtv-kaist/cs458-spring24/assets/55888021/4a7366f8-32d7-4eb5-b9ab-00ae957eddc1)

**Comment by yheechan** [comment]
Thank you for the solution, I have followed your instructions and checked that it works.
