### ISSUE TITLE
[HW2] Method for replaying grep commands 

### ISSUE THREAD

**Issue by RiceBiscuits** [swtv-kaist/cs458-spring24#5]
I have a question about the format of a test_script that contains grep commands.
My grep commands contains some special symbols that can escape "" or ''. 
As a result, some of characters in the commands are considered to syntax errors when I try to execute my 'test_script' as a shell script.

For example, 
```
./test_script: line 51: syntax error near unexpected token `)'
```

Because of this issue, I have some trouble with fixing the error for each test case without affecting the coverage.
But it works fine if I execute commands with subprocess module in a python script.

Thus I wonder how TA evaluate test cases (grep commands in test_script) to measure the branch coverage. 
Is it requirement that "test_script" file can be executed as a shell script?
If it is not, can I submit test_script and a python script that can read the test_script and execute grep commands?

**Comment by swtv-kaist** [comment]
> Is it requirement that "test_script" file can be executed as a shell script?\

Yes, your ```test_script``` should be an executable shell script so that TA can execute it.
Your ```test_script``` can execute a python file, if you like.

**Comment by RiceBiscuits** [comment]
Thank you for your kind answer.
