### ISSUE TITLE
HW3 - In which file should I add manual probes?

### ISSUE THREAD

**Issue by tncks0121** [swtv-kaist/cs458-spring24#7]
The first page of the homework pdf says "Your manual testing code should be contained in `tcas-mod-mcdc.c`"

Part II says "Manually add your own probing code to measure MCDC coverage of the following 8 compound predicates in
`tcas-mod-mcdc.c`", so I thought I should edit `tcas-mod-mcdc.c`.

Part IV says "Manually generate test inputs to achieve high branch coverage for tcas-mod-mcdc.c (w/o your probes)"

So, to solve Part II-III, `tcas-mod-mcdc.c` should contain the probes, but to solve Part I and IV, it should not contain the probes.

And, the first page says "Entire testing process (compiling and executing tcas-mod-mcdc.c, applying gcov, etc.) should be performed by executing `run.sh`" It seems I have to edit `tcas-mod-mcdc.c` within `run.sh`, which seems weird to me.

1. Is editing `tcas-mod-mcdc.c` within `run.sh` intended?
2. Am I allowed to create a new file like `tcas-mod-mcdc-withprobes.c` which consists of `tcas-mod-mcdc.c` with added probes?

**Comment by swtv-kaist** [comment]
>1. Is editing tcas-mod-mcdc.c within run.sh intended?

No

> 2. Am I allowed to create a new file like tcas-mod-mcdc-withprobes.c which consists of tcas-mod-mcdc.c with added probes?

Yes.
