### ISSUE TITLE
[HW3] Part IV branch coverage

### ISSUE THREAD

**Issue by leejy12** [swtv-kaist/cs458-spring24#8]
I have two questions about Part IV.

1. Problem 3b asks for branch coverage of test inputs. Does it mean the total branch coverage achieved by all test inputs combined or branch coverage for each test input?
2. Should we ignore problem 3c as per https://github.com/swtv-kaist/cs458-spring24/issues/6#issuecomment-2044425205?
   > Thus, you don't have to report branch coverage information per function in your HW.

**Comment by swtv-kaist** [comment]
> Problem 3b asks for branch coverage of test inputs. Does it mean the total branch coverage achieved by all test inputs combined or branch coverage for each test input?

The toal branch coverage achieved by all test inputs combined

> Should we ignore problem 3c as per https://github.com/swtv-kaist/cs458-spring24/issues/6#issuecomment-2044425205?

No. You should not ignore problem 3c.  Still you can answer 3.c w/o branch coverage information per function from ```gcov``` (think how).
